version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_lab2
    env_file: ".env"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_HOST_PORT}:3306
